security:
  # Since symfony/security-bundle 6.2: The "enable_authenticator_manager" option at "security" is deprecated.
  enable_authenticator_manager: true

  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    custom_user_provider:
      id: App\Core\Security\UserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    voting_system:
      lazy: true
      pattern: ^/api/v1
      provider: custom_user_provider
      custom_authenticators:
        - App\Core\Security\ApiTokenAuthenticator

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/api/doc, roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
