# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
#            - '../src/Entity/' # commented out since we want to autowire it in services
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    ### GLOBAL SERVICES ###

    App\Core\REST\Service\ApiSerializerService: ~

    ### GLOBAL SUBSCRIBERS/LISTENERS ###

    App\Core\REST\Subscriber\RequestSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    App\Core\REST\Subscriber\ResponderSubscriber:
        tags:
            - { name: kernel.event_subscriber }
